apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-server
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-server
  template:
    metadata:
      labels:
        app: nats-server
    spec:
      containers:
        - name: nats-server
          image: nats:2.12
          ports:
            - containerPort: 4222
