
apiVersion: v1
kind: Service
metadata:
  name: nats-server-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: nats-server
  ports:
    - port: 4222
      protocol: TCP
      targetPort: 4222
