
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster-deployment
  namespace: project
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: todo-broadcaster
          image: docker.io/iku1/todo_broadcaster:4.6.0
          imagePullPolicy: Always
          env:
            - name: NATS_URL
              value: "nats://nats-server-svc:4222"
            - name: APPRISE_URL
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secret
                  key: APPRISE_URL
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
