apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo-backend # This is the app as declared in the deployment.
  ports:
    - port: 80 # This is a port that is available to the cluster, in this case it can be ~ anything
      protocol: TCP
      targetPort: 5005 # This is the target port
