apiVersion: batch/v1
kind: CronJob
metadata:
  name: add-random-todo-cronjob
  namespace: project
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-random-todo
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              export URL=$(curl -Ls -o /dev/null -w '%{url_effective}' https://en.wikipedia.org/wiki/Special:Random)
              curl -X POST -H 'Content-Type: application/json' \
              -d "{\"todo\": \"Read about $URL\"}" \
              http://todo-backend-svc:80/todos
          restartPolicy: OnFailure
