apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../volumes/persistent_cache.yml
  - ../../volumes/persistent_imgcache_claim.yaml
  # Broadcaster
  - ../todo_broadcaster/manifests/00-nats.yml
  - ../todo_broadcaster/manifests/01-nats-service.yaml
  - ../todo_broadcaster/manifests/02-deployment.yaml
  # Backend
  - ../todo_backend/manifests/01-database.yaml
  - ../todo_backend/manifests/02-deployment.yaml
  - ../todo_backend/manifests/03-service.yaml
  - ../todo_backend/manifests/04-ingress.yaml
  - ../todo_backend/manifests/05-cron.yaml
  # Frontend
  - ../todo_app/manifests/deployment.yaml
  - ../todo_app/manifests/service.yaml
