apiVersion: v1
kind: Secret
metadata:
    name: pg-password
    namespace: project
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:D10h/FLZMU4gqEOCBK0p2b08hQNr+Vml+UmNVSMR5fXgAZqkNx66vV/uUtg=,iv:38IJg1fzAjy9NE77B/tfn/sq6NS+xOK9TUOM0Ni0YdE=,tag:HwuyaVYoCbSa/6+lahQ4pg==,type:str]
sops:
    age:
        - recipient: age1gfaw77w5zne6u04etrhlahpk4usepvchdsdamjukwwsjtcxr6a9s37xa7e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaHNHSU8rTFFBRGw2Z2Jy
            QktpZEFuTGowdUlvWkZ0cEFmMkR0SS8zL2djCkQyNGJFTkRwb1J2VWU4QU5iTm9t
            dUlLN0x5ZkFQbjMycHU3eFlNRDJ0aWcKLS0tIEt4NWVzS1FqaUlCUlJSc3NzYjBP
            N3B1U1RhK05nSS9xWGpySzM4R1I1U2sKAEOybyBVLmUGmPDW5IwZ/PewLdysVd+f
            jPGqK04HWkogSpRWeGY7dLRdsjMcTE+vPpSI5Xf6XNYQIGXPjP0DiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T05:52:51Z"
    mac: ENC[AES256_GCM,data:ZMkVf47RgrYaJXEPVu0oW9MFV6KOLOIOnLRfPNikFcj43xRCcY9YqlnB6klorJpelEq8jZuAElKkRSSEK6I1BKpKaOCH01m8ddj1+eANpHjzDFhlcFxzVvSYprk7/EmiMAKMyUbzhJhREDRqeyqC1rMnGeVDuwy6BM+DHx1Hsdk=,iv:1tEEEiFZjQ32X42YM9sQbqKh8rV+QAw7T4g7ptMYK54=,tag:GIzXKoycdYaOprY3GVPPZg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.10.2
