apiVersion: v1
kind: Service
metadata:
  name: greeter-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: greeter
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5008

