apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../namespaces/00-execrcies.yaml
  - 00-persistent_log_claim.yaml
  - 01-env-config.yaml
  - 02-infofile-config.yaml
  - 03-deployment.yaml
  - 04-service.yaml
  - 05-gateway.yaml
  - 06-route.yaml
