apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: exercises
  name: ping-pong-rollout
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ping-pong
  strategy:
    canary:
      steps:
      - analysis:
          templates:
          - templateName: cpu-usage
      - setWeight: 50
      - pause:
          duration: 1m
      - setWeight: 75
      - pause:
          duration: 1m
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: docker.io/iku1/ping_pong:4.4.6
          imagePullPolicy: Always
          env:
            - name: POSTGRES_URL
              value: "postgresql://postgres@postgres-svc"
            - name: PORT
              value: "5001"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            httpGet:
              path: /
              port: 5001
