apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
   - 00-namespace.yaml
   - 01-database.yaml
   - 02-deployment.yaml
   - 03-service.yaml
   - 05-gateway.yaml
   - 06-route.yaml

