name: Release the Project

on:
  delete:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  BRANCH: ${{ github.ref_name }}

jobs:
  delete-kubernetes-namespace:
    name: Delete Kubernetes namespace corresponding to a branch
    environment: GKE
    runs-on: ubuntu-latest

    steps:
      - name: Set Kubernetes namespace to use
        run: |
          if [ "$BRANCH" = "master" ]; then
            NAMESPACE="project"
          else
            NAMESPACE="$(echo $BRANCH)"
          fi

          if [ "$NAMESPACE" = "project" ]; then
            echo "Refusing to delete default namespace 'project'."
            exit 1
          fi

          echo "NAMESPACE=$NAMESPACE" | tee "$GITHUB_ENV"

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: gcloud info

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: Install kubectl CLI
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Delete namespace
        run: |-
          echo "Deleting namespace ${{ env.NAMESPACE }}"
          kubectl delete namespace ${{ env.NAMESPACE }} --ignore-not-found --wait=false  || true
